### ISSUE TITLE
Synchronising problem

### ISSUE THREAD

**Issue by ArkAnimax** [Multibit-Legacy/multibit-website-legacy#32]
I bought bitcoins and sent them to my account on multibit, but they never arrived. So i did what the support site said and tried resetting the blockchain from the day before. The thing is, after i do that, it keeps "synchronising" forever. i had left my computer in for 3 hours and nothing, I have a screenshot of my messages up to that point if it helps.
![bit](https://f.cloud.github.com/assets/4916458/734493/b147c3c8-e2cc-11e2-9ef7-7c07e248f3a9.png)

**Comment by sipsapa** [comment]
I m having this same problem, except when I go to user/library/application support - there is no multibit folders - i should say, I have defo installed multiit and it shows and opens in my applications folder, there is just no files in app support - what am i doing wrong - help would be greatly appreciated

**Comment by bitcoin-solutions** [comment]
If you look in the Messages window immendiately after opening MultiBit you can see where it is writing wallets by default. It's the 'application data directory'. Have a look in there.
